language: go

go:
  - 1.6
# We shouldn't need to install anything because we use vendoring.
install:
- echo "Don't run anything."

# Check non-vendored code for formatting.
script: diff -u <(echo -n) <(gofmt -l -s . | grep -v vendor)
script: ./test.sh
